version: '3.9'

services:
  app:
    container_name: user-segmentation
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - dus-backend

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "${LOCAL_DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - dus-backend

  minio:
    image: minio/minio
    command: storage server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - storage-data:/data
    networks:
      - dus-backend

networks:
  dus-backend:
    driver: bridge

volumes:
  pg-data:
  minio-data: