version: '3.9'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./scripts:/root/scripts
      - ./secrets:/root/secrets
      - ./docs:/root/docs
    depends_on:
      - postgres
    networks:
      - dus-backend

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "${LOCAL_DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - dus-backend

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    env_file:
      - .env
    volumes:
      - ./scripts/nginx/setup.sh:/setup.sh
      - ./secrets/certs:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - dus-backend

networks:
  dus-backend:
    driver: bridge

volumes:
  pg-data: